### ISSUE TITLE
Python Error for julian_day_orbit.py

### ISSUE THREAD

**Issue by powerofdream2020** [cmontalvo251/aerospace#1]
Hi Sir,

I found your project quite interesting, and I tried to run julian_day_orbit, from the universe directory. My platform is PyCharm 2022, on windows 10.

I ran into some error as follows:
 
ERROR: Could not find a version that satisfies the requirement mio (from versions: none)
ERROR: No matching distribution found for mio

I tried to install the mio module with command, without any luck.

Thanks for the time to take a look at it.

**Comment by cmontalvo251** [comment]
Aw dang. I'm sorry. That python file is here

https://github.com/cmontalvo251/Python/blob/master/io/mio.py

**Comment by cmontalvo251** [comment]
I added some comments to this python script to direct the user to the proper repos with supplemental files. Going to go ahead and close this issue.
