### ISSUE TITLE
Quaternions2EulerAngles issue

### ISSUE THREAD

**Issue by jdvb7299** [cmontalvo251/aerospace#2]
Hello Prof Montalvo,

I am wondering if the edits you made to Quaternions2EulerAngles may be causing some unforeseen consequences.
I've been iterating on the sim to tune my rw controller gain, and every few iterations I would get an error saying that atan could not support complex number.
When I uncommented your revisions, namely:
s = size(q0123);
if s(1) == 4 && s(2) == 1
    q0123=q0123';
end

as well as:
ptp = real(ptp);

I've since no received that error.

Also, I added an output to send ptpout to an excel csv, which works well. Once I commented out the code above, all of the euler angles were showing as complex numbers (all with +0i). After I uncommented this code, the euler angles no longer have this suffix.

Cheers, thanks a million for uploading and continuing to improve this code! Looking forward to addition of desaturation scheme!

**Comment by cmontalvo251** [comment]
You're totally right. I think quaternions have this issue during numerical simulation which is why I had it there in the first place. 

I'll fix this asap and make a comment so I don't make this same mistake again.

**Comment by cmontalvo251** [comment]
real() function uncommented and notes added to prevent this issue in the future.
